services:
  # -----------------------
  # MySQL para QA
  # -----------------------
  mysql-qa:
    image: mysql:8
    container_name: mysql-qa
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: QA
      MYSQL_USER: facu
      MYSQL_PASSWORD: facu123
    volumes:
      - mysql_qa_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # -----------------------
  # MySQL para PROD (separado)
  # -----------------------
  mysql-prod:
    image: mysql:8
    container_name: mysql-prod
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: PROD
      MYSQL_USER: facu
      MYSQL_PASSWORD: facu123
    volumes:
      - mysql_prod_data:/var/lib/mysql
    ports:
      - "3308:3306"
  # -----------------------
  # App QA
  # -----------------------
  app-qa:
    image: rorteg3/app:dev
    container_name: app-qa
    environment:
      APP_ENV: "qa"
      DATABASE_URL: "mysql://facu:facu123@mysql-qa:3306/QA"
    ports:
      - "5001:5000"
    depends_on:
      - mysql-qa

  # -----------------------
  # App PROD
  # -----------------------
  app-prod:
    image: rorteg3/app:dev
    container_name: app-prod
    environment:
      APP_ENV: "production"
      DATABASE_URL: "mysql://facu:facu123@mysql-prod:3306/PROD"
    ports:
      - "5002:5000"
    depends_on:
      - mysql-prod

volumes:
  mysql_qa_data:
  mysql_prod_data: